# Assignment 03 Solution

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Create Dataset

In [2]:
df = pd.DataFrame(np.random.randn(10, 4),
                  index=pd.date_range('2021-07-18', periods=10),
                  columns=['a', 'b', 'c', 'd'])
display(df)

                   a         b         c         d
2021-07-18  0.473521 -0.061977 -0.951464  0.231355
2021-07-19 -0.923299  0.837941  0.153566 -1.873546
2021-07-20 -0.586864 -0.016279  1.453017 -0.797889
2021-07-21 -0.131598 -0.578934  0.794499 -1.464230
2021-07-22  0.310802  0.404877 -0.778935 -1.626528
2021-07-23 -0.452076  0.589868 -0.684428 -1.128725
2021-07-24  0.310258  0.721477 -2.035483  0.226579
2021-07-25 -1.141266  0.237748  0.294942 -0.308621
2021-07-26  1.196627 -1.221206 -1.098916  1.332770
2021-07-27  0.653788  0.167353 -0.062301 -0.331955

## Task 1

In [3]:
# Task 1: Create a new column and store the logarithmic values for column d
# Constraint: Without using np.log() directly on Series

def log_value(x):
    return x if x <= 0 else np.log(x)

df['log_d'] = [log_value(x) for x in df['d']]
display(df)

                   a         b         c         d     log_d
2021-07-18  0.473521 -0.061977 -0.951464  0.231355 -1.463802
2021-07-19 -0.923299  0.837941  0.153566 -1.873546 -1.873546
2021-07-20 -0.586864 -0.016279  1.453017 -0.797889 -0.797889
2021-07-21 -0.131598 -0.578934  0.794499 -1.464230 -1.464230
2021-07-22  0.310802  0.404877 -0.778935 -1.626528 -1.626528
2021-07-23 -0.452076  0.589868 -0.684428 -1.128725 -1.128725
2021-07-24  0.310258  0.721477 -2.035483  0.226579 -1.484662
2021-07-25 -1.141266  0.237748  0.294942 -0.308621 -0.308621
2021-07-26  1.196627 -1.221206 -1.098916  1.332770  0.287260
2021-07-27  0.653788  0.167353 -0.062301 -0.331955 -0.331955

## Task 2

In [4]:
# Task 2: Create a new column where:
# Negative values of column d remain same
# Positive values are replaced with their log values

df['transformed_d'] = [x if x < 0 else np.log(x) for x in df['d']]
display(df)

                   a         b         c         d     log_d  transformed_d
2021-07-18  0.473521 -0.061977 -0.951464  0.231355 -1.463802      -1.463802
2021-07-19 -0.923299  0.837941  0.153566 -1.873546 -1.873546      -1.873546
2021-07-20 -0.586864 -0.016279  1.453017 -0.797889 -0.797889      -0.797889
2021-07-21 -0.131598 -0.578934  0.794499 -1.464230 -1.464230      -1.464230
2021-07-22  0.310802  0.404877 -0.778935 -1.626528 -1.626528      -1.626528
2021-07-23 -0.452076  0.589868 -0.684428 -1.128725 -1.128725      -1.128725
2021-07-24  0.310258  0.721477 -2.035483  0.226579 -1.484662      -1.484662
2021-07-25 -1.141266  0.237748  0.294942 -0.308621 -0.308621      -0.308621
2021-07-26  1.196627 -1.221206 -1.098916  1.332770  0.287260       0.287260
2021-07-27  0.653788  0.167353 -0.062301 -0.331955 -0.331955      -0.331955

## Task 3

In [5]:
# Task 3: Create a column from column a that returns:
# 'yes' if the value is even (after converting to integer)
# 'no' otherwise

df['even_a'] = ['yes' if int(x) % 2 == 0 else 'no' for x in df['a']]
display(df)

,a,b,c,d,log_d,transformed_d,even_a
2021-07-18,0.473521,-0.061977,-0.951464,0.231355,-1.463802,-1.463802,yes
2021-07-19,-0.923299,0.837941,0.153566,-1.873546,-1.873546,-1.873546,yes
2021-07-20,-0.586864,-0.016279,1.453017,-0.797889,-0.797889,-0.797889,yes
2021-07-21,-0.131598,-0.578934,0.794499,-1.464230,-1.464230,-1.464230,yes
2021-07-22,0.310802,0.404877,-0.778935,-1.626528,-1.626528,-1.626528,yes
2021-07-23,-0.452076,0.589868,-0.684428,-1.128725,-1.128725,-1.128725,yes
2021-07-24,0.310258,0.721477,-2.035483,0.226579,-1.484662,-1.484662,yes
2021-07-25,-1.141266,0.237748,0.294942,-0.308621,-0.308621,-0.308621,no
2021-07-26,1.196627,-1.221206,-1.098916,1.332770,0.287260,0.287260,no
2021-07-27,0.653788,0.167353,-0.062301,-0.331955,-0.331955,-0.331955,yes

## Task 4

In [6]:
# Task 4: Create a new column with index values

df['index_col'] = [i for i in df.index]
display(df)

,a,b,c,d,log_d,transformed_d,even_a,index_col
2021-07-18,0.473521,-0.061977,-0.951464,0.231355,-1.463802,-1.463802,yes,2021-07-18
2021-07-19,-0.923299,0.837941,0.153566,-1.873546,-1.873546,-1.873546,yes,2021-07-19
2021-07-20,-0.586864,-0.016279,1.453017,-0.797889,-0.797889,-0.797889,yes,2021-07-20
2021-07-21,-0.131598,-0.578934,0.794499,-1.464230,-1.464230,-1.464230,yes,2021-07-21
2021-07-22,0.310802,0.404877,-0.778935,-1.626528,-1.626528,-1.626528,yes,2021-07-22
2021-07-23,-0.452076,0.589868,-0.684428,-1.128725,-1.128725,-1.128725,yes,2021-07-23
2021-07-24,0.310258,0.721477,-2.035483,0.226579,-1.484662,-1.484662,yes,2021-07-24
2021-07-25,-1.141266,0.237748,0.294942,-0.308621,-0.308621,-0.308621,no,2021-07-25
2021-07-26,1.196627,-1.221206,-1.098916,1.332770,0.287260,0.287260,no,2021-07-26
2021-07-27,0.653788,0.167353,-0.062301,-0.331955,-0.331955,-0.331955,yes,2021-07-27

## Task 5

In [7]:
# Task 5: Split index (date) into three new columns: year, month, and day

df['year'] = [str(i).split('-')[0] for i in df.index]
df['month'] = [str(i).split('-')[1] for i in df.index]
df['day'] = [str(i).split('-')[2].split(' ')[0] for i in df.index]
display(df)

,a,b,c,d,log_d,transformed_d,even_a,index_col,year,month,day
2021-07-18,0.473521,-0.061977,-0.951464,0.231355,-1.463802,-1.463802,yes,2021-07-18,2021,07,18
2021-07-19,-0.923299,0.837941,0.153566,-1.873546,-1.873546,-1.873546,yes,2021-07-19,2021,07,19
2021-07-20,-0.586864,-0.016279,1.453017,-0.797889,-0.797889,-0.797889,yes,2021-07-20,2021,07,20
2021-07-21,-0.131598,-0.578934,0.794499,-1.464230,-1.464230,-1.464230,yes,2021-07-21,2021,07,21
2021-07-22,0.310802,0.404877,-0.778935,-1.626528,-1.626528,-1.626528,yes,2021-07-22,2021,07,22
2021-07-23,-0.452076,0.589868,-0.684428,-1.128725,-1.128725,-1.128725,yes,2021-07-23,2021,07,23
2021-07-24,0.310258,0.721477,-2.035483,0.226579,-1.484662,-1.484662,yes,2021-07-24,2021,07,24
2021-07-25,-1.141266,0.237748,0.294942,-0.308621,-0.308621,-0.308621,no,2021-07-25,2021,07,25
2021-07-26,1.196627,-1.221206,-1.098916,1.332770,0.287260,0.287260,no,2021-07-26,2021,07,26
2021-07-27,0.653788,0.167353,-0.062301,-0.331955,-0.331955,-0.331955,yes,2021-07-27,2021,07,27

## Task 6

In [8]:
# Task 6: Create a column that returns the weekday name of the index manually (without using .day_name())

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
df['weekday'] = [days[i.weekday()] for i in df.index]
display(df)

,a,b,c,d,log_d,transformed_d,even_a,index_col,year,month,day,weekday
2021-07-18,0.473521,-0.061977,-0.951464,0.231355,-1.463802,-1.463802,yes,2021-07-18,2021,07,18,Sunday
2021-07-19,-0.923299,0.837941,0.153566,-1.873546,-1.873546,-1.873546,yes,2021-07-19,2021,07,19,Monday
2021-07-20,-0.586864,-0.016279,1.453017,-0.797889,-0.797889,-0.797889,yes,2021-07-20,2021,07,20,Tuesday
2021-07-21,-0.131598,-0.578934,0.794499,-1.464230,-1.464230,-1.464230,yes,2021-07-21,2021,07,21,Wednesday
2021-07-22,0.310802,0.404877,-0.778935,-1.626528,-1.626528,-1.626528,yes,2021-07-22,2021,07,22,Thursday
2021-07-23,-0.452076,0.589868,-0.684428,-1.128725,-1.128725,-1.128725,yes,2021-07-23,2021,07,23,Friday
2021-07-24,0.310258,0.721477,-2.035483,0.226579,-1.484662,-1.484662,yes,2021-07-24,2021,07,24,Saturday
2021-07-25,-1.141266,0.237748,0.294942,-0.308621,-0.308621,-0.308621,no,2021-07-25,2021,07,25,Sunday
2021-07-26,1.196627,-1.221206,-1.098916,1.332770,0.287260,0.287260,no,2021-07-26,2021,07,26,Monday
2021-07-27,0.653788,0.167353,-0.062301,-0.331955,-0.331955,-0.331955,yes,2021-07-27,2021,07,27,Tuesday

## Final DataFrame

In [9]:
# Display the final state of the DataFrame after all tasks
display(df.head())

,a,b,c,d,log_d,transformed_d,even_a,index_col,year,month,day,weekday
2021-07-18,0.473521,-0.061977,-0.951464,0.231355,-1.463802,-1.463802,yes,2021-07-18,2021,07,18,Sunday
2021-07-19,-0.923299,0.837941,0.153566,-1.873546,-1.873546,-1.873546,yes,2021-07-19,2021,07,19,Monday
2021-07-20,-0.586864,-0.016279,1.453017,-0.797889,-0.797889,-0.797889,yes,2021-07-20,2021,07,20,Tuesday
2021-07-21,-0.131598,-0.578934,0.794499,-1.464230,-1.464230,-1.464230,yes,2021-07-21,2021,07,21,Wednesday
2021-07-22,0.310802,0.404877,-0.778935,-1.626528,-1.626528,-1.626528,yes,2021-07-22,2021,07,22,Thursday